include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  plugins:
    - custom_lint
  language:
    strict-inference: true
    strict-raw-types: false
  errors:
    constant_identifier_names: ignore
    invalid_annotation_target: ignore

formatter:
  page_width: 80

linter:
  rules:
    lines_longer_than_80_chars: false
    omit_local_variable_types: false
    avoid_positional_boolean_parameters: false
    one_member_abstracts: false
    public_member_api_docs: false
    always_use_package_imports: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    prefer_typing_uninitialized_variables: true
    avoid_types_on_closure_parameters: true
    type_annotate_public_apis: true
    type_init_formals: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_single_quotes: true
    cancel_subscriptions: true
    avoid_empty_else: true
    avoid_unused_constructor_parameters: true
    empty_catches: true
    empty_statements: true
    always_declare_return_types: true
    use_to_and_as_if_applicable: true
    avoid_setters_without_getters: true
    avoid_return_types_on_setters: true
    hash_and_equals: true
    use_full_hex_values_for_flutter_colors: true
    use_late_for_private_fields_and_variables: true
    unnecessary_getters_setters: true
    directives_ordering: true
    curly_braces_in_flow_control_structures: true
